### ISSUE TITLE
您好，想问问您生成的.danmu文件该如何打开使用？

### ISSUE THREAD

**Issue by vaallx** [Mtcno/DouYuRecorder#2]

**Comment by Mtcno** [comment]
”TimeCount={0},user={1},text={2},col={3}“
这个只是保留了相关的弹幕的时间、文本、颜色。没实现播放器所以看不了。danmu文件的时间是相对于视频进度。我本来想写过转成ssa字幕格式，并且要找ssa格式资料，就暂时罢工啦。
